version: "3.9"

services:
  api:
    build: ./fastapi-backend
    ports:
      - "8000:8000"

    volumes:
      - ./fastapi-backend:/app
    
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todos
    volumes:
      - todo:/data/db

volumes:
  todo:
